version: '3.9'

services:
  app:
    container_name: fsap_app
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --log-config ./config.ini
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/home/code
      - ./tmp:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    container_name: fsap_db
    image: postgres:14-alpine
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data
      - ./tmp:/tmp
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: fsap_redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    entrypoint: redis-server --appendonly yes

  celeryd: &celery
    container_name: celeryd
    build: &celery-build
      dockerfile: docker/Dockerfile.celeryd
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./worker:/opt/app/worker
      - ./app:/opt/app/app
      - ./docker/worker.sh:/opt/app/worker.sh
      - ./tmp:/opt/app/tmp
    env_file:
      - .env

#  celerybeat:
##    <<: *celery
#    container_name: celerybeat
#    build:
##      <<: *celery-build
#      dockerfile: docker/Dockerfile.celeryd.celerybeat
#    depends_on:
#      - celeryd
#    env_file:
#      - .env

  flower:
    container_name: celery-flower
    image: mher/flower:0.9.7
    restart: always
    command: [ 'flower', '--broker=redis://:$REDIS_PASSWORD@redis:$REDIS_PORT/14', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis
      - celeryd

volumes:
  fastapi_postgres_data: {}